name: fatigue-detector
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - opencv
  - numpy
  - pandas
  - pillow
  - scikit-learn
  - tk
  - pip
  - pip:
      - mediapipe
      - ultralytics
      - joblib
