name: CI Fatigue Detector

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          python-version: 3.10

      - name: Remove previous environment (if exists)
        run: conda env remove --name fatigue-detector || true

      - name: Create environment
        run: conda env create --name fatigue-detector -f environment.yml

      - name: Test GUI launch
        shell: bash -l {0}
        run: |
          conda activate fatigue-detector
          python -c "import start_gui"
